# Generated by Django 4.1.7 on 2023-03-28 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 28, 9, 53, 23, 118398, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 28, 9, 53, 27, 847230, tzinfo=datetime.timezone.utc), verbose_name='Дата и время обновления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 28, 9, 53, 43, 369643, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления'),
        ),
    ]
